### ISSUE TITLE
exported build does not load: 404 File Not Found for `Build/SECVRITY.json` file

### ISSUE THREAD

**Issue by cvan** [caseyyee/secvrity#3]
```
Uncaught SyntaxError: Unexpected token < in JSON at position 0
```

![screenshot 33](https://user-images.githubusercontent.com/203725/32368474-0953e9ea-c043-11e7-8078-5295d316a54c.png)
![screenshot 34](https://user-images.githubusercontent.com/203725/32368478-0df04bc4-c043-11e7-8270-3b8e44336808.png)
![screenshot 35](https://user-images.githubusercontent.com/203725/32368487-1827605a-c043-11e7-8552-14f3a0103d45.png)
![screenshot 37](https://user-images.githubusercontent.com/203725/32368490-1b9f4db0-c043-11e7-9d40-db2dd2a0de97.png)

**Comment by caseyyee** [comment]
Fixed with https://github.com/caseyyee/secvrity/commit/f84bbb3586fbe8bff2fc743015ab55120b6dda6b
